# Generated by Django 2.2.13 on 2020-07-07 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('denger', 'high'), ('info', 'normal'), ('success', 'low')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
