# Generated by Django 2.2.13 on 2020-07-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200707_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='memo',
            field=models.TextField(max_length=100),
        ),
    ]
